// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/v1/_middleware.ts";
import * as $1 from "./routes/api/v1/authentication/index.ts";
import * as $2 from "./routes/api/v1/conversions/[from]/[into].ts";
import * as $3 from "./routes/api/v1/conversions/_multiplier_of.ts";
import * as $4 from "./routes/api/v1/transfers/[id]/_commit.ts";
import * as $5 from "./routes/api/v1/transfers/[id]/index.ts";
import * as $6 from "./routes/api/v1/transfers/[id]/items/[item_id].ts";
import * as $7 from "./routes/api/v1/transfers/[id]/items/index.ts";
import * as $8 from "./routes/api/v1/transfers/_validators.ts";
import * as $9 from "./routes/api/v1/transfers/index.ts";
import * as $10 from "./routes/api/v1/transmutes/index.ts";
import * as $11 from "./routes/api/v1/warehouses/[id]/index.ts";
import * as $12 from "./routes/api/v1/warehouses/[id]/stocks.ts";
import * as $13 from "./routes/api/v1/warehouses/index.ts";
import * as $14 from "./routes/index.tsx";
import * as $15 from "./routes/sandbox/index.tsx";
import * as $$0 from "./islands/Sandbox.tsx";

const manifest = {
  routes: {
    "./routes/api/v1/_middleware.ts": $0,
    "./routes/api/v1/authentication/index.ts": $1,
    "./routes/api/v1/conversions/[from]/[into].ts": $2,
    "./routes/api/v1/conversions/_multiplier_of.ts": $3,
    "./routes/api/v1/transfers/[id]/_commit.ts": $4,
    "./routes/api/v1/transfers/[id]/index.ts": $5,
    "./routes/api/v1/transfers/[id]/items/[item_id].ts": $6,
    "./routes/api/v1/transfers/[id]/items/index.ts": $7,
    "./routes/api/v1/transfers/_validators.ts": $8,
    "./routes/api/v1/transfers/index.ts": $9,
    "./routes/api/v1/transmutes/index.ts": $10,
    "./routes/api/v1/warehouses/[id]/index.ts": $11,
    "./routes/api/v1/warehouses/[id]/stocks.ts": $12,
    "./routes/api/v1/warehouses/index.ts": $13,
    "./routes/index.tsx": $14,
    "./routes/sandbox/index.tsx": $15,
  },
  islands: {
    "./islands/Sandbox.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
